### ISSUE TITLE
libpng12-0 requirements are not user friendly for Ubuntu

### ISSUE THREAD

**Issue by unixtreme** [valarnin/ffxiv-tools#19]
Tested in `20.04 LTS`.
Especially the i386 lib, there aren't really any pre-compiled deb packages that will work due to a change in lib folders.
I had to make my own to be able to install it.
The 64 bit lib can be installed from a third party repo.

Normally I wouldn't open a bug report for this but considering Ubuntu is one of the most popular distros and that this dependency was already broken in previous versions it would probably be worth looking into. I haven't really spent any time verifying what the dependency is used for so I'm unaware of how complicated it would be to move to `libpng16`.

**Comment by valarnin** [comment]
This was fixed on the `lutris-wine-6` branch, see commit https://github.com/valarnin/ffxiv-tools/commit/a0e10684fab7971f8ec4d30d7ca84ff64176413f

Considering support for Proton versions newer than 5.20 via Steam is still not possible due to bubblewrap, using lutris+XIVLauncher and using the `lutris-wine-6` branch is the recommended setup currently.

Given that, I'm not sure it's worth backporting those changes to the main branch. Thoughts?

**Comment by unixtreme** [comment]
Makes sense to me, in that case I'd clarify in the documentation that `XIVLauncher` users have a specific feature branch they should use. Specially if said branch is the new recommended setup. That's just a thought though.

Thanks!
